import { Injectable } from '@angular/core';
import { Project } from "../models/project.model";

@Injectable({
  providedIn: 'root'
})
export class ProjectsService {

  projects: Project[] = [new Project("Casa Mantay",
    "Casa Mantay befindet sich in Cusco, Peru. Das Ziel des Projektes ist es, in einem geschützten Umfeld für das Heranwachsen der Kinder zu sorgen und den jungen Müttern eine Ausbildung zu ermöglichen. Das Haus dient vor allem als Zufluchtsort für minderjährige schwangere Mädchen und minderjährige Mütter mit ihren Kindern, die auf sich alleine gestellt sind. Während ihres Aufenthaltes lernen die Mädchen ihre Aufgaben als Mutter wahrzunehmen und zu geniessen.",
    "assets/casa_mantay.jpg", "Peru", "Casa Mantay befindet sich in Cusco, Peru. Das Ziel des Projektes ist es, in einem geschützten Umfeld für das Heranwachsen der Kinder zu sorgen und den jungen Müttern eine Ausbildung zu ermöglichen. Das Haus dient vor allem als Zufluchtsort für minderjährige schwangere Mädchen und minderjährige Mütter mit ihren Kindern, die auf sich alleine gestellt sind. Während ihres Aufenthaltes lernen die Mädchen ihre Aufgaben als Mutter wahrzunehmen und zu geniessen. Das Haus Mantay ist ein zweistöckiges, rosarotes Haus in der Nähe eines grossen Marktes. Inmitten befindet sich ein grosser, viereckiger Innenhof mit roten und blauen Türen (Foto Innenhof). Im unteren Stock sind verschiedene Zimmer aufzufinden: ein Büro für das Personal, zwei Räume für die Betreuung der Kinder, ein Fernsehzimmer, das Esszimmer und die Küche. Im zweiten Stock befinden sich die Schlafzimmer der Mädchen mit ihren Kindern. Im Haus leben 24 minderjährige Mädchen im Alter von 12 bis 18 Jahren, davon 12 Mütter mit ihren Kindern. Durch Betreuerinnen vor Ort werden die Mädchen in ihrem Alltag begleitet. Jeden Monat kommen neue Freiwillige aus verschiedenen Ländern, um das Projekt mit ihrer Arbeit zu unterstützen. Jedes Mädchen hat ihre eigene Geschichte."),
    new Project("Fundación Sanctuary Colombia", "Der Sitz des Projektes Fundación Sanctuary Colombia befindet sich in Bogotá, Kolumbien und setzt sich für die Verbesserung der Lebensqualität von Kindern, jungen Erwachsenen und Familien in den ärmsten Regionen von Chocó, Kolumbien ein. Sie kämpfen gegen die Armut, die Ungleichheit und die Unsicherheit der verschiedenen Bevölkerungsgruppen, die den Chocó bewohnen.",
      "assets/fundation_sanctuary.jpg", "Kolumbien", "Der Sitz des Projektes Fundación Sanctuary Colombia befindet sich in Bogotá, Kolumbien und setzt sich für die Verbesserung der Lebensqualität von Kindern, jungen Erwachsenen und Familien in den ärmsten Regionen von Chocó, Kolumbien ein. Sie kämpfen gegen die Armut, die Ungleichheit und die Unsicherheit der verschiedenen Bevölkerungsgruppen, die den Chocó bewohnen. Um dieses Ziel zu erreichen planen sie kleine Projekte und Events für die betroffenen Personen. Primär wird das Geld für Lebensmittel und Kleider eingesetzt. Die Fundation setzt sich aber auch für das Recht auf Bildung ein und verteilt den Kindern jährlich Schulmaterial. Für die Freizeit werden Tätigkeiten geplant, wie zum Beispiel ein gemeinsamer Kinobesuch mit den Kindern und ihren Eltern. Jährlich zu Weihnachten bekommen die Kinder mit Hilfe einer grösseren Spendenaktion Spielsachen, Kleider, Schuhe und Lebensmittel."),
    new Project("«Madres Migrantes», Fundación Casa Viña", "Die Stiftung Casa Viña befindet sich in Quito, Ecuador. Sie setzt sich für die Gemeinschaft und insbesondere für die Bedürftigsten ein. In Ecuador leben heute mehr als eine halbe Million Venezolaner*innen – viele davon sind alleinstehende Mütter. Die Stiftung Casa Viña hilft Müttern mit Migrationshintergrund (die meisten von ihnen sind Venezolanerinnen oder Kolumbianerinnen) in prekären Situationen.",
      "assets/madres-migrantes.jpg", "Ecuador", "Die Stiftung Casa Viña befindet sich in Quito, Ecuador. Sie setzt sich für die Gemeinschaft und insbesondere für die Bedürftigsten ein. In Ecuador leben heute mehr als eine halbe Million Venezolaner*innen – viele davon sind alleinstehende Mütter. Die Stiftung Casa Viña hilft Müttern mit Migrationshintergrund (die meisten von ihnen sind Venezolanerinnen oder Kolumbianerinnen) in prekären Situationen. Erstens wurde einigen Müttern und deren Familienmitgliedern zu Beginn des Projektes (Juli 2020) eine temporäre Unterkunft zur Verfügung gestellt. Zweitens wird ihnen fast jeden Samstag ein Lebensmittelpaket gespendet, das ihre Grundbedürfnisse abdecken und somit für Nahrungsmittelsicherheit sorgen soll. Drittens erhalten die Mütter von der Stiftung psychologische und integrative Unterstützung. Durch Vorträge, Workshops und andere Gruppenaktivitäten geleitet von Expert*innen, werden die Mütter bezüglich Selbstständigkeit und Unabhängigkeit bestärkt. Nebst diesen Dienstleistungen organisiert die Stiftung Casa Viña auch konkrete «Berufsausbildungskurse» für die Mütter. Den Projektteilnehmerinnen werden theoretische und praktische Instrumente bezüglich der Entwicklung von eigenen Unternehmen sowie ein kleines Startkapital bereitgestellt. Beispiele der verschiedenen Fachbereiche sind Finanzen, Öffentlichkeitsarbeit, Marketing oder Verkauf. Dabei geht es um Themen wie Selbstverwaltung, die Förderung von Spenden sowie die aktive Partizipation und Mitarbeit bei der Stiftung. Einige der Mütter, die bereits seit Beginn des Projektes dabei sind, engagieren sich heute freiwillig, um Neuankömmlingen zu helfen. Die Stiftung arbeitet hinsichtlich des Projektes «Madres Migrantes» in Kollaboration mit «World Vision», deren Mitarbeitende beispielsweise Workshops oder Schulungen mit den Müttern durchführen. Während den Workshops gibt es freiwillige Mitwirkende, die gleichzeitig mit den Kindern Zeit verbringen und dadurch die Mütter entlasten."),
    new Project("Situation in der Schweiz", "Auch in der Schweiz leben viele alleinstehende Mütter unter prekären Lebensbedingungen. Durch prägende Lebensereignisse wie Scheidung, Tod oder andere Schicksalsschläge rutschen viele Mütter mit ihren Kindern in die Armut.",
      "assets/situation_schweiz.jpg", "Schweiz", "Auch in der Schweiz leben viele alleinstehende Mütter unter prekären Lebensbedingungen. Durch prägende Lebensereignisse wie Scheidung, Tod oder andere Schicksalsschläge rutschen viele Mütter mit ihren Kindern in die Armut. Oftmals müssen sie die Hilfe des Sozialamts in Anspruch nehmen, wodurch sie finanziell abhängig werden. Das Sozialamt kann nicht alle Bereiche abdecken und genau dort wollen wir ansetzen. Wir möchten den betroffenen Müttern primär eine Aus- oder Weiterbildung ermöglichen, damit sie wieder selbstständig und finanziell unabhängig werden können.")]

  constructor() { }

  public getProjects(): Project[] {
    return this.projects;
  }

  public findProject(title: string): Project | undefined {
      return this.projects.find(project => project.title.includes(title));
  }
}
